groups:
    - bash
    - developer
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    sublime_text_packages:
        -
            name: Dockerfile Syntax Highlighting
            source: https://github.com/asbjornenge/Dockerfile.tmLanguage
            branch: 0.2.2
        -
            name: EditorConfig
            source: https://github.com/sindresorhus/editorconfig-sublime
            branch: st3
        -
            name: Gist
            source: https://github.com/condemil/Gist
            branch: master
        -
            name: Git
            source: https://github.com/kemayo/sublime-text-git
            branch: master
        -
            name: Github Tools
            source: https://github.com/temochka/sublime-text-2-github-tools
            branch: master
        -
            name: Google Spell Check
            source: https://github.com/noahcoad/google-spell-check
            branch: st3
        -
            name: Jekyll
            source: https://github.com/23maverick23/sublime-jekyll
            branch: v2.1.1
        -
            name: Markdown Extended
            source: https://github.com/jonschlinkert/sublime-markdown-extended
            branch: master
        -
            name: Markdown Preview
            source: https://github.com/revolunet/sublimetext-markdown-preview
            branch: 1.1.12
        -
            name: Less
            source: https://github.com/danro/LESS-sublime
            branch: master
    dotfiles:
        vimusers:
            - root
            - simon
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
                - vim-css-color: https://github.com/ap/vim-css-color
        git:
            name: Simon Dittlmann
            email: simon@itnotes.de
    osxdefaults:
        computername: Simons-MBP
    homebrewalt:
        apps:
            - git
            - rsync
            - git-extras
        cask_apps:
            - google-drive
            - dropbox
            - evernote
            - 1password
            - vlc
            - hipchat
            - adobe-photoshop-lightroom
            - boot2docker
            - flashlight
            - couleurs
            - vagrant-manager
            - vagrant
            - vmware-fusion
            - virtualbox
            - cyberduck
            - android-file-transfer
            - gimp
            - growlnotify
            - webstorm
            - iterm2
            - silverlight
            - flash
            - perian
            - music-manager
            - textmate
    nodejs:
        apps:
            - bower
            - grunt
            - grunt-cli